# Your name and what you do
name: Guillem Orpinell
bio: Product Manager

description: Guillem's portfolio

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://urpi.ninja

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
linkedin: urpi
twitter: urpininja
medium: urpi
github: urpizu
email: guillem.orpinell@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - HTML, Jade
    - CSS (Stylus, Sass, Less)
    - Javascript, NodeJS
    - AngularJS, ReactJS
    - Java, Android
    - Python
    - MySQL - MongoDB    
    - Git    

# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    Bookify:
        name: 📚 Bookify app — Design Challenge
        description: My approach and thinking process in a mobile app framing, research, ideation and design.
        url: https://paper.dropbox.com/doc/Bookify-app-Design-Challenge--AcwVIIBQy4d~u20OgvQioY9QAg-zOTAj0V24gpjcnf0wUVOb
    Flatmates:
        name: 🏘️ Flatmates app — UX/UI case study
        description: A product design exploring the scope and the visual outcome for a renting rooms app.
        url: https://medium.com/@urpi/flatmates-app-a-ux-case-study-2dddea5e64d9
    Spreadsheets:
        name: 🕹️ Productivity tools in Game Design
        description: A set of improvements on quality and efficiency by designing features, processes and tools.
        url: https://medium.com/@urpi/spreadsheet-tools-in-game-design-57511eac68c


# do you want to display the theme attribution? true or false
footer: false

# Enable animations? true or false
animation: true
